using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Avalonia.Generators.StaticBindingGenerator
{
    /// <summary>
    /// Generates C# code for StaticBinding OnDataContextChanged implementations.
    /// </summary>
    internal class StaticBindingCodeGenerator
    {
        private const string GeneratedCodeAttribute = "[global::System.CodeDom.Compiler.GeneratedCode(\"AvaloniaStaticBindingGenerator\", \"1.0.0.0\")]";
        private const string ExcludeFromCodeCoverageAttribute = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";

        /// <summary>
        /// Generates the complete partial class with OnDataContextChanged for the given bindings.
        /// </summary>
        public string GenerateCode(
            string className,
            string nameSpace,
            string? dataType,
            IEnumerable<StaticBindingInfo> bindings,
            bool enableBatching = true,
            int batchDelayMs = 10)
        {
            var bindingsList = bindings.ToList();

            if (!bindingsList.Any())
                return string.Empty;

            var sb = new StringBuilder();

            // File header
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This code was generated by the Avalonia StaticBinding Source Generator.");
            sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using Avalonia;");
            sb.AppendLine("using Avalonia.Controls;");
            sb.AppendLine("using Avalonia.Data.Converters;");

            if (enableBatching)
            {
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Threading;");
                sb.AppendLine("using System.Threading.Tasks;");
            }

            sb.AppendLine();
            sb.AppendLine($"namespace {nameSpace}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            // Generate fields
            GenerateFields(sb, bindingsList, dataType);

            // Generate InitializeComponent_Generated method
            GenerateInitializeComponentGenerated(sb, bindingsList);

            // Generate OnDataContextChanged override
            GenerateOnDataContextChanged(sb, bindingsList, dataType, enableBatching);

            // Generate PropertyChanged handler
            if (bindingsList.Any(b => b.Mode == StaticBindingMode.OneWay) && !string.IsNullOrEmpty(dataType))
            {
                if (enableBatching)
                {
                    GenerateBatchedPropertyChangedHandler(sb, bindingsList, dataType!, batchDelayMs);
                }
                else
                {
                    GenerateImmediatePropertyChangedHandler(sb, bindingsList, dataType!);
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void GenerateFields(StringBuilder sb, List<StaticBindingInfo> bindings, string? dataType)
        {
            sb.AppendLine("        // Generated fields for StaticBinding");
            sb.AppendLine();

            // Control references (distinct by control name)
            var distinctControls = bindings
                .GroupBy(b => b.ControlName)
                .Select(g => g.First())
                .ToList();

            foreach (var binding in distinctControls)
            {
                sb.AppendLine($"        private global::{binding.ControlType}? _gen_{binding.ControlName};");
            }

            // Converter references (distinct by converter key)
            var distinctConverters = bindings
                .Where(b => b.HasConverter)
                .GroupBy(b => b.ConverterResourceKey)
                .Select(g => g.First())
                .ToList();

            foreach (var binding in distinctConverters)
            {
                sb.AppendLine($"        private global::Avalonia.Data.Converters.IValueConverter? _gen_converter_{binding.ConverterResourceKey};");
            }

            // DataContext reference
            if (!string.IsNullOrEmpty(dataType))
            {
                sb.AppendLine($"        private global::{dataType}? _gen_currentDataContext;");
            }

            sb.AppendLine();
        }

        private void GenerateInitializeComponentGenerated(StringBuilder sb, List<StaticBindingInfo> bindings)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Initializes StaticBinding infrastructure. Called from InitializeComponent.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        {GeneratedCodeAttribute}");
            sb.AppendLine($"        {ExcludeFromCodeCoverageAttribute}");
            sb.AppendLine("        partial void InitializeComponent_Generated();");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Internal implementation of InitializeComponent_Generated.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        {GeneratedCodeAttribute}");
            sb.AppendLine($"        {ExcludeFromCodeCoverageAttribute}");
            sb.AppendLine("        private void InitializeComponent_GeneratedImpl()");
            sb.AppendLine("        {");
            sb.AppendLine("            var nameScope = this.FindNameScope();");
            sb.AppendLine();

            // Find and cache controls (distinct by control name)
            var distinctControls = bindings
                .GroupBy(b => b.ControlName)
                .Select(g => g.First())
                .ToList();

            foreach (var binding in distinctControls)
            {
                sb.AppendLine($"            _gen_{binding.ControlName} = nameScope?.Find<global::{binding.ControlType}>(\"{binding.ControlName}\");");
            }

            // Find and cache converters (distinct by converter key)
            var distinctConverters = bindings
                .Where(b => b.HasConverter)
                .GroupBy(b => b.ConverterResourceKey)
                .Select(g => g.First())
                .ToList();

            foreach (var binding in distinctConverters)
            {
                sb.AppendLine($"            _gen_converter_{binding.ConverterResourceKey} = this.FindResource(\"{binding.ConverterResourceKey}\") as global::Avalonia.Data.Converters.IValueConverter;");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GenerateOnDataContextChanged(
            StringBuilder sb,
            List<StaticBindingInfo> bindings,
            string? dataType,
            bool enableBatching)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Handles DataContext changes and updates bound properties.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        {GeneratedCodeAttribute}");
            sb.AppendLine($"        {ExcludeFromCodeCoverageAttribute}");
            sb.AppendLine("        protected override void OnDataContextChanged(EventArgs e)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnDataContextChanged(e);");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(dataType))
            {
                // Unsubscribe from old DataContext
                var hasOneWayBindings = bindings.Any(b => b.Mode == StaticBindingMode.OneWay);
                if (hasOneWayBindings)
                {
                    sb.AppendLine("            // Unsubscribe from old DataContext");
                    sb.AppendLine("            if (_gen_currentDataContext != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine("                _gen_currentDataContext.PropertyChanged -= OnGeneratedPropertyChanged;");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }

                // Cast to DataType
                sb.AppendLine($"            _gen_currentDataContext = DataContext as global::{dataType};");
                sb.AppendLine();
                sb.AppendLine("            if (_gen_currentDataContext != null)");
                sb.AppendLine("            {");

                // Generate property assignments
                foreach (var binding in bindings)
                {
                    GeneratePropertyAssignment(sb, binding, "                ");
                }

                // Subscribe to PropertyChanged for OneWay bindings
                if (hasOneWayBindings)
                {
                    sb.AppendLine();
                    sb.AppendLine("                // Subscribe to property changes");
                    sb.AppendLine("                _gen_currentDataContext.PropertyChanged += OnGeneratedPropertyChanged;");
                }

                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GeneratePropertyAssignment(StringBuilder sb, StaticBindingInfo binding, string indent)
        {
            sb.AppendLine($"{indent}// Binding: {binding.ControlName}.{binding.TargetProperty} = {binding.Path}");
            sb.AppendLine($"{indent}if (_gen_{binding.ControlName} != null)");
            sb.AppendLine($"{indent}{{");

            var sourceExpression = $"_gen_currentDataContext.{binding.Path}";

            if (binding.HasConverter)
            {
                // Apply converter
                sb.AppendLine($"{indent}    if (_gen_converter_{binding.ConverterResourceKey} != null)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        var sourceValue = {sourceExpression};");
                sb.AppendLine($"{indent}        var convertedValue = _gen_converter_{binding.ConverterResourceKey}.Convert(");
                sb.AppendLine($"{indent}            sourceValue,");
                sb.AppendLine($"{indent}            typeof({binding.TargetPropertyType ?? "object"}),");
                sb.AppendLine($"{indent}            null, // ConverterParameter not supported in MVP");
                sb.AppendLine($"{indent}            System.Globalization.CultureInfo.CurrentCulture);");

                if (!string.IsNullOrEmpty(binding.TargetNullValue))
                {
                    sb.AppendLine($"{indent}        _gen_{binding.ControlName}.{binding.TargetProperty} = ({binding.TargetPropertyType})(convertedValue ?? {binding.TargetNullValue});");
                }
                else if (!string.IsNullOrEmpty(binding.FallbackValue))
                {
                    sb.AppendLine($"{indent}        _gen_{binding.ControlName}.{binding.TargetProperty} = ({binding.TargetPropertyType})(convertedValue ?? {binding.FallbackValue});");
                }
                else
                {
                    sb.AppendLine($"{indent}        _gen_{binding.ControlName}.{binding.TargetProperty} = ({binding.TargetPropertyType})convertedValue;");
                }
                sb.AppendLine($"{indent}    }}");
            }
            else if (!string.IsNullOrEmpty(binding.StringFormat))
            {
                // Apply string format
                sb.AppendLine($"{indent}    var sourceValue = {sourceExpression};");
                sb.AppendLine($"{indent}    _gen_{binding.ControlName}.{binding.TargetProperty} = string.Format(\"{binding.StringFormat}\", sourceValue);");
            }
            else
            {
                // Direct assignment
                if (!string.IsNullOrEmpty(binding.TargetNullValue))
                {
                    sb.AppendLine($"{indent}    var sourceValue = {sourceExpression};");
                    sb.AppendLine($"{indent}    _gen_{binding.ControlName}.{binding.TargetProperty} = sourceValue ?? {binding.TargetNullValue};");
                }
                else if (!string.IsNullOrEmpty(binding.FallbackValue))
                {
                    sb.AppendLine($"{indent}    var sourceValue = {sourceExpression};");
                    sb.AppendLine($"{indent}    _gen_{binding.ControlName}.{binding.TargetProperty} = sourceValue ?? {binding.FallbackValue};");
                }
                else
                {
                    sb.AppendLine($"{indent}    _gen_{binding.ControlName}.{binding.TargetProperty} = {sourceExpression};");
                }
            }

            sb.AppendLine($"{indent}}}");
        }

        private void GenerateImmediatePropertyChangedHandler(
            StringBuilder sb,
            List<StaticBindingInfo> bindings,
            string dataType)
        {
            var oneWayBindings = bindings.Where(b => b.Mode == StaticBindingMode.OneWay).ToList();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Handles property changes on the DataContext.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        {GeneratedCodeAttribute}");
            sb.AppendLine($"        {ExcludeFromCodeCoverageAttribute}");
            sb.AppendLine("        private void OnGeneratedPropertyChanged(object? sender, PropertyChangedEventArgs e)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_gen_currentDataContext == null || string.IsNullOrEmpty(e.PropertyName))");
            sb.AppendLine("                return;");
            sb.AppendLine();
            sb.AppendLine("            switch (e.PropertyName)");
            sb.AppendLine("            {");

            foreach (var binding in oneWayBindings)
            {
                sb.AppendLine($"                case nameof(global::{dataType}.{binding.Path}):");
                GeneratePropertyAssignment(sb, binding, "                    ");
                sb.AppendLine("                    break;");
                sb.AppendLine();
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GenerateBatchedPropertyChangedHandler(
            StringBuilder sb,
            List<StaticBindingInfo> bindings,
            string dataType,
            int batchDelayMs)
        {
            var oneWayBindings = bindings.Where(b => b.Mode == StaticBindingMode.OneWay).ToList();

            sb.AppendLine("        // Batching state");
            sb.AppendLine("        private CancellationTokenSource? _gen_updateBatchCts;");
            sb.AppendLine($"        private const int BatchDelayMs = {batchDelayMs};");
            sb.AppendLine("        private readonly object _gen_batchLock = new object();");
            sb.AppendLine("        private bool _gen_hasPendingUpdates = false;");
            sb.AppendLine("        private readonly HashSet<string> _gen_pendingProperties = new HashSet<string>();");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Handles property changes on the DataContext with batching.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        {GeneratedCodeAttribute}");
            sb.AppendLine($"        {ExcludeFromCodeCoverageAttribute}");
            sb.AppendLine("        private void OnGeneratedPropertyChanged(object? sender, PropertyChangedEventArgs e)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_gen_currentDataContext == null || string.IsNullOrEmpty(e.PropertyName))");
            sb.AppendLine("                return;");
            sb.AppendLine();
            sb.AppendLine("            lock (_gen_batchLock)");
            sb.AppendLine("            {");
            sb.AppendLine("                _gen_pendingProperties.Add(e.PropertyName);");
            sb.AppendLine();
            sb.AppendLine("                _gen_updateBatchCts?.Cancel();");
            sb.AppendLine("                _gen_updateBatchCts = new CancellationTokenSource();");
            sb.AppendLine("                var token = _gen_updateBatchCts.Token;");
            sb.AppendLine();
            sb.AppendLine("                if (!_gen_hasPendingUpdates)");
            sb.AppendLine("                {");
            sb.AppendLine("                    _gen_hasPendingUpdates = true;");
            sb.AppendLine();
            sb.AppendLine("                    Task.Delay(BatchDelayMs, token).ContinueWith(");
            sb.AppendLine("                        _ =>");
            sb.AppendLine("                        {");
            sb.AppendLine("                            if (!token.IsCancellationRequested)");
            sb.AppendLine("                            {");
            sb.AppendLine("                                Avalonia.Threading.Dispatcher.UIThread.Post(() =>");
            sb.AppendLine("                                {");
            sb.AppendLine("                                    ApplyBatchedUpdates();");
            sb.AppendLine("                                });");
            sb.AppendLine("                            }");
            sb.AppendLine("                        },");
            sb.AppendLine("                        token,");
            sb.AppendLine("                        TaskContinuationOptions.OnlyOnRanToCompletion,");
            sb.AppendLine("                        TaskScheduler.Default);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate ApplyBatchedUpdates method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Applies batched property updates with BeginUpdate/EndUpdate.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        {GeneratedCodeAttribute}");
            sb.AppendLine($"        {ExcludeFromCodeCoverageAttribute}");
            sb.AppendLine("        private void ApplyBatchedUpdates()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_gen_currentDataContext == null)");
            sb.AppendLine("                return;");
            sb.AppendLine();
            sb.AppendLine("            HashSet<string> propertiesToUpdate;");
            sb.AppendLine();
            sb.AppendLine("            lock (_gen_batchLock)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!_gen_hasPendingUpdates)");
            sb.AppendLine("                    return;");
            sb.AppendLine();
            sb.AppendLine("                propertiesToUpdate = new HashSet<string>(_gen_pendingProperties);");
            sb.AppendLine("                _gen_pendingProperties.Clear();");
            sb.AppendLine("                _gen_hasPendingUpdates = false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var visualRoot = this.GetVisualRoot() as Avalonia.Controls.TopLevel;");
            sb.AppendLine("            visualRoot?.BeginUpdate();");
            sb.AppendLine();
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (var propertyName in propertiesToUpdate)");
            sb.AppendLine("                {");
            sb.AppendLine("                    switch (propertyName)");
            sb.AppendLine("                    {");

            foreach (var binding in oneWayBindings)
            {
                sb.AppendLine($"                        case nameof(global::{dataType}.{binding.Path}):");
                GeneratePropertyAssignment(sb, binding, "                            ");
                sb.AppendLine("                            break;");
                sb.AppendLine();
            }

            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                visualRoot?.EndUpdate();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
